apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: import-tests-go-crbehsmv-import
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/import-tests-go-crbehsmv-import:7cbb4837aa2495be0752f87b9f8756391b03df62
          name: container-image
